# Generated by Django 5.0.2 on 2024-03-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libtools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
