# Generated by Django 3.2.12 on 2024-03-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libtools', '0003_book_status_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='images/default_cover.png', null=True, upload_to='images/'),
        ),
    ]
